name = "NestedQuadratures"
uuid = "be84acb1-8bce-4f57-b94b-f01ee9e129e1"
authors = ["astroEduardo <72969764+astroEduardo@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
